### ISSUE TITLE
Official release

### ISSUE THREAD

**Issue by boukenka** [JeremyLikness/SqliteWasmHelper#12]
Hello @JeremyLikness,

Thanks for the package!
Do you plan to maintain / propose updated packages in the future?

Thank you for any response.

**Comment by boukenka** [comment]
@JeremyLikness Hello. Could you provide a feedback please.

**Comment by JeremyLikness** [comment]
Yes, I'll work on one. No specific ETA as I have to fix some CI/CD issues and would like to address the outstanding bugs, but I will get there. It's not a huge effort and many thanks for others who contributed to the upgrade to .NET  7! Thanks for asking.

**Comment by boukenka** [comment]
@JeremyLikness Thank you for you answer.
