### ISSUE TITLE
Option to run `Database.MigrateAsync` instead of ` Database.CreateAsync`

### ISSUE THREAD

**Issue by ysmoradi** [JeremyLikness/SqliteWasmHelper#23]
https://github.com/JeremyLikness/SqliteWasmHelper/blob/main/SqliteWasmHelper/SqliteWasmDbContextFactory.cs#L80

![image](https://github.com/JeremyLikness/SqliteWasmHelper/assets/5352980/b41d5bff-a8cd-43a6-98dd-5c67301b0e55)

We're relying on migrations in our project. Could you please accept option to run the followings instead:

```cs
await ctx.Database.MigrateAsync();
```

**Comment by Eddie-Hartman** [comment]
See here: https://github.com/JeremyLikness/SqliteWasmHelper/pull/22
