### ISSUE TITLE
A way to disable console logging?

### ISSUE THREAD

**Issue by cmsw97** [JeremyLikness/SqliteWasmHelper#36]
First of all, great package, thanks!

Just one question/request: Is there a way to prevent logging SQL queries to the developer console?

**Comment by ysmoradi** [comment]
Greetings
This is simply relying on ef core integration with Microsoft.Extensions.Logging
Refer to Microsoft docs to configure / disable ef core logging.

Note that this project is not maintained anymore and you can find more information about its replacement [here](https://github.com/bitfoundation/bitplatform-samples/tree/main/videos/Bit.Besql) and fill new issues [here](https://github.com/bitfoundation/bitplatform).
