### ISSUE TITLE
C# double properties will not persist to sqlite

### ISSUE THREAD

**Issue by RaminFadaeian** [JeremyLikness/SqliteWasmHelper#6]
**Describe the bug**
Any attempt to persist a c# object with double property throws "Uncaught (in promise)" error

**To Reproduce**
Try saving a following c# object to sqlite database:
  public class ConcreteModel
  {
      public int Id { get; set; }
      public string Label { get; set; } = "Default";
      public double Density { get; set; } = 150; // pcf
  }

**Expected behavior**
The object can successfully persist to DB if the double property "Density" is commented out.

**Screenshots**
![image](https://user-images.githubusercontent.com/80645307/176093757-4aa1d06f-6789-46fd-aafe-973285ba0a87.png)

**Comment by DougBowen72** [comment]
Not surprisingly float doesn't work either but change to decimal and it works.

**Comment by RaminFadaeian** [comment]
The work around at this point for me was to use string conversion of double and float numbers when reading/writing to database. It works just fine. Getting this to work for me was far more important than performance hit. So I am fine with string conversion in the middle as long as it works. 

protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
{
  configurationBuilder.Properties<double>()
      .HaveConversion<string>();

  base.ConfigureConventions(configurationBuilder);
}

**Comment by JeremyLikness** [comment]
So do you think this behavior should be built in, or this code should be published as a workaround for those who run into it?

**Comment by RaminFadaeian** [comment]
Looks like this issue was resolved in recent version of SQLitePCLRaw.bundle_e_sqlite3 (2.1.6) package. I tested it extensively and it works fine with double and float numbers.

Closing the issue.
