### ISSUE TITLE
Issue migrating to .Net 7 

### ISSUE THREAD

**Issue by RaminFadaeian** [JeremyLikness/SqliteWasmHelper#8]
**Describe the bug**
An unhandled exception is thrown when migrating to .Net 7

![Screenshot 2022-09-25 132925](https://user-images.githubusercontent.com/80645307/192163842-9fe45540-81e7-492f-add0-a66ddcb22975.png)

**To Reproduce**
1. Clone current project
2. Change target framework to net7.0
3. update Nuget packages
5. See error

![Screenshot 2022-09-25 133229](https://user-images.githubusercontent.com/80645307/192164370-d5d59284-e06e-4486-871d-956fd6ec27fd.png)

**Additional context**
I have minimal knowledge of JS. I did my best to figure out why virtual file system is unavailable with no success. I appreciate any help.

**Comment by nickbeau** [comment]
I have created a  PR (See https://github.com/JeremyLikness/SqliteWasmHelper/pull/7) which resolves the issue in dotnet 7

**Comment by RaminFadaeian** [comment]
Very much appreciated @nickbeau . 
This issue is closed now. 
PS. I should have checked out PRs before submitting this issue

**Comment by snow-jallen** [comment]
The window.Module.FS fix in this PR would sure be handy, I can't use this with .NET 7 until this is released.  Now that v7 has officially RTW'd could this PR be updated to use release version numbers and merged?
