### ISSUE TITLE
Database not saved to cache after bulk operations.

### ISSUE THREAD

**Issue by jimnorth55** [JeremyLikness/SqliteWasmHelper#9]
I am using [EFCore.BulkExtensions](https://github.com/borisdj/EFCore.BulkExtensions) in conjunction with your SqliteWasmHelper, to do a bulk insert of records downloaded from my WebApi.    After the BulkInsert completes, the in-memory copy of the Sqlite DB contains the records, however the browser-cache backup file is not updated.     Looking at your Ctx_SavedChanges event handler in SqliteWasmDbContextFactory, I am assuming that your hook into the DB context's SavedChanges is not firing, or is firing with an EntitiesSavedCount of 0. 

Can your API be used to  force the DB to be saved to cache?  If so, what is the proper way to do this?

Thanks,
Jim

**Comment by quartsystem** [comment]
Workaround:
```
            var first = ctx.entities.FirstOrDefault();
            if (first != null)
            {
                ctx.Entry(first).State = EntityState.Modified;
                SaveChanges();
            }
```

**Comment by jimnorth55** [comment]
Works perfectly!  Thank you.

**Comment by JeremyLikness** [comment]
Great point. I'll add an API to force save and then see if I can hook it into bulk operations automatically.
